name: inthecube
version: '0.1'
summary: A tiny cube in a giant maze. Platform/puzzle game.
description: |
  InTheCube is a platform/puzzle game.

  You are a little cubic robot (1cm³) sent in a bigger one.

  Your agility and reflection will be challenged for you to go through more
  than 30 levels. You will discover many different mechanism (laser, mirrors,
  moving blocks, ...)

  Strange machines are found in the most advanced levels.
icon: "./resources/img/img_hero.png"
grade: stable
confinement: strict
base: core18

apps:
  inthecube:
    command: desktop-launch ${SNAP}/bin/inthecube
    plugs:
    - audio-playback
    - opengl
    - x11
    - pulseaudio

parts:

  cmake:
    source: https://github.com/Kitware/CMake
    source-type: git
    source-depth: 1
    plugin: cmake
    override-build: |
      mkdir -p build
      cd build
      cmake \
        -DCMAKE_INSTALL_PREFIX=$SNAPCRAFT_STAGE/cmake \
        $SNAPCRAFT_PART_SRC
      make -j ${SNAPCRAFT_PARALLEL_BUILD_COUNT}
      make install
    build-packages:
    - build-essential
    - libssl-dev
    - libncurses5-dev
    stage-packages:
    - libssl1.1
    - libncurses5
    - libtinfo5
    prime: []

  desktop-glib-only:
    plugin: make
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: glib-only
    build-packages:
    - libglib2.0-dev
    stage-packages:
    - libglib2.0-bin

  inthecube:
    after:
    - cmake
    - desktop-glib-only
    plugin: cmake
    source: https://github.com/ArthurSonzogni/inthecube
    source-type: git
    source-depth: 1
    stage-packages:
    - libgl1-mesa-glx
    - libpulse0
    build-packages:
    - libglu-dev
    - libpulse-dev
    - xorg-dev
    override-build: |
      $SNAPCRAFT_STAGE/cmake/bin/cmake \
        -DCMAKE_INSTALL_PREFIX=$SNAPCRAFT_PART_INSTALL \
        -DCMAKE_BUILD_TYPE=RelWithDebInfo \
        $SNAPCRAFT_PART_SRC
      make -j ${SNAPCRAFT_PARALLEL_BUILD_COUNT}
      make install

passthrough:
  title: inthecube
  license: MIT
