name: inthecube
version: '0.1'
summary: A tiny cube in a giant maze. Platform/puzzle game.
description: |
  InTheCube is a platform/puzzle game.

  You are a little cubic robot (1cm³) sent in a bigger one.

  Your agility and reflection will be challenged for you to go through more
  than 30 levels. You will discover many different mechanism (laser, mirrors,
  moving blocks, ...)

  Strange machines are found in the most advanced levels.
icon: ./resources/img/img_hero.png
grade: stable
confinement: strict
base: core18
apps:
  inthecube:
    command: desktop-launch ${SNAP}/usr/local/bin/inthecube
    plugs:
      - opengl
      - pulseaudio
      - x11
parts:

  cmake:
    source: https://github.com/Kitware/CMake
    source-type: git
    source-depth: 1
    plugin: cmake
    override-build: |
      mkdir -p build
      cd build
      cmake \
        -DCMAKE_INSTALL_PREFIX=$SNAPCRAFT_STAGE/cmake \
        $SNAPCRAFT_PART_SRC
      make -j 4
      make install

  inthecube:
    after: [cmake]
    plugin: cmake
    source: https://github.com/ArthurSonzogni/InTheCube
    source-type: git
    source-depth: 1
    stage-packages:
      - libgl1-mesa-glx
      - libpulse0
      - libpng16-16
    build-packages:
      - libglu-dev
      - libssl1.0-dev
      - libpulse-dev
      - xorg-dev
    override-build: |
      $SNAPCRAFT_STAGE/cmake/bin/cmake \
        -DCMAKE_INSTALL_PREFIX=$SNAPCRAFT_PART_INSTALL/usr/local \
        -DCMAKE_BUILD_TYPE=Release \
        $SNAPCRAFT_PART_SRC
      make -j 4
      make install

  desktop-glib-only:
    plugin: make
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: glib-only
    build-packages:
    - libglib2.0-dev
    stage-packages:
    - libglib2.0-bin

passthrough:
  title: InTheCube
  license: MIT
